### ISSUE TITLE
Ejercicios de Proposiciones Lógicas

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Eddi3mendoz#1]
[Ejercicios Lógica Proposicional.pdf](https://github.com/user-attachments/files/17387828/Ejercicios.Logica.Proposicional.pdf)

**Comment by irwingsael** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100
20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
